---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stratum-config-scripts
  labels:
    app: stratum
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- range $key, $val := .Values.chassis_config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  stratum-config: |
    #!/bin/sh
    set -e -x
    # Mount from Helm Values, chassis_config
    REMOTE_CHASSIS_CONFIG=/opt/configs/$NODE_NAME
    LOCAL_CHASSIS_CONFIG=$CFG_MOUNT/chassis_config.pb.txt
    if [ -f $REMOTE_CHASSIS_CONFIG ]; then
        if [ -f $LOCAL_CHASSIS_CONFIG ] && [ ! -f $LOCAL_CHASSIS_CONFIG.old ]; then
            mv $LOCAL_CHASSIS_CONFIG $LOCAL_CHASSIS_CONFIG.old
        fi
        cp $REMOTE_CHASSIS_CONFIG $LOCAL_CHASSIS_CONFIG
    fi
