{{- if .Values.podsecuritypolicy.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: 1-stratum
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - 'configMap'
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/dev"
    - pathPrefix: "/sys"
    - pathPrefix: "/var/log"
    - pathPrefix: "/lib/modules/4.19.0-12-2-amd64"
    - pathPrefix: "/etc/sonic"
    - pathPrefix: "/config"
  hostNetwork: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
{{- end }}
