{{- if .Values.podsecuritypolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role:psp:stratum
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:stratum
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
